# Generated by Django 2.1 on 2019-07-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190628_1650'),
        ('users', '0002_auto_20190702_0054'),
    ]

    operations = [
    ]
