# Generated by Django 2.1 on 2019-07-12 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=-1, max_digits=3)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data_type', models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date')], editable=False, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='lesson/pdf')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default0.jpg', upload_to='course_image/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('n_rating', models.IntegerField(default=0)),
                ('n_subs', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ManyToManyField(to='store.Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('TYPE', models.CharField(choices=[('radio', 'radio'), ('text', 'text'), ('checkbox', 'checkbox')], default='radio', max_length=10)),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=30)),
                ('time', models.IntegerField()),
                ('random', models.BooleanField(blank=True, default=False)),
                ('number', models.IntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(blank=True, max_length=50, null=True)),
                ('q2', models.CharField(blank=True, max_length=50, null=True)),
                ('q3', models.CharField(blank=True, max_length=50, null=True)),
                ('q4', models.CharField(blank=True, max_length=50, null=True)),
                ('q5', models.CharField(blank=True, max_length=50, null=True)),
                ('q6', models.CharField(blank=True, max_length=50, null=True)),
                ('q7', models.CharField(blank=True, max_length=50, null=True)),
                ('q8', models.CharField(blank=True, max_length=50, null=True)),
                ('q9', models.CharField(blank=True, max_length=50, null=True)),
                ('q10', models.CharField(blank=True, max_length=50, null=True)),
                ('q11', models.CharField(blank=True, max_length=50, null=True)),
                ('q12', models.CharField(blank=True, max_length=50, null=True)),
                ('q13', models.CharField(blank=True, max_length=50, null=True)),
                ('q14', models.CharField(blank=True, max_length=50, null=True)),
                ('q15', models.CharField(blank=True, max_length=50, null=True)),
                ('q16', models.CharField(blank=True, max_length=50, null=True)),
                ('q17', models.CharField(blank=True, max_length=50, null=True)),
                ('q18', models.CharField(blank=True, max_length=50, null=True)),
                ('q19', models.CharField(blank=True, max_length=50, null=True)),
                ('q20', models.CharField(blank=True, max_length=50, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('t_score', models.IntegerField(null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to='store.Post')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Quiz'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
        ),
    ]
