# Generated by Django 2.2.2 on 2019-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
