# Generated by Django 2.2.2 on 2019-07-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190701_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=3),
        ),
    ]
