# Generated by Django 2.2.2 on 2019-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190703_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortby', models.CharField(max_length=15)),
            ],
        ),
    ]
