# Generated by Django 2.1 on 2019-06-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_lesson'),
        ('store', '0003_auto_20190621_1929'),
    ]

    operations = [
    ]
