# Generated by Django 2.2.2 on 2019-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_question_quiz_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
