# Generated by Django 2.2.2 on 2019-07-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sortby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sortby',
        ),
    ]
