# Generated by Django 2.2.2 on 2019-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_20190621_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default0.jpg', upload_to='course_image/'),
        ),
    ]
