# Generated by Django 2.1 on 2019-06-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190623_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='pdf',
            new_name='file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
        ),
    ]
