# Generated by Django 2.2.2 on 2019-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_sortby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='n_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='n_subs',
            field=models.IntegerField(default=0),
        ),
    ]
