# Generated by Django 2.1 on 2019-06-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190623_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
        ),
    ]
