# Generated by Django 2.2.2 on 2019-07-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190706_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='TYPE',
            field=models.CharField(choices=[('radio', 'radio'), ('text', 'text'), ('checkbox', 'checkbox')], default='radio', max_length=10),
        ),
    ]
