# Generated by Django 2.2.2 on 2019-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190706_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
