# Generated by Django 2.1 on 2019-06-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20190623_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
            preserve_default=False,
        ),
    ]
