# Generated by Django 2.1 on 2019-06-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190624_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
        ),
    ]
