# Generated by Django 2.2.2 on 2019-06-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='store.Post'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='users',
            field=models.ManyToManyField(to='store.Post'),
        ),
    ]
