# Generated by Django 2.1 on 2019-06-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190625_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
            preserve_default=False,
        ),
    ]
