# Generated by Django 2.1 on 2019-06-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190625_1848'),
        ('store', '0011_auto_20190624_1717'),
    ]

    operations = [
    ]
