# Generated by Django 2.1 on 2019-06-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_merge_20190625_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Post'),
        ),
    ]
