# Generated by Django 2.2.2 on 2019-07-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190709_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='t_score',
        ),
    ]
