# Generated by Django 2.2.2 on 2019-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190625_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='users',
            field=models.ManyToManyField(null=True, to='store.Post'),
        ),
    ]
