# Generated by Django 2.2.2 on 2019-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190709_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
