# Generated by Django 2.2.2 on 2019-07-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190710_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='index',
        ),
    ]
