# Generated by Django 2.2.2 on 2019-07-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20190711_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='random',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
