# Generated by Django 2.2.2 on 2019-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_quiz_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='random',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
