# Generated by Django 2.2.2 on 2019-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20190711_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
