# Generated by Django 2.2.2 on 2019-07-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_quiz_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
