# Generated by Django 2.2.2 on 2019-07-11 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20190711_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
