# Generated by Django 2.2.2 on 2019-07-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20190711_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='result',
            name='q9',
        ),
    ]
