# Generated by Django 2.2.2 on 2019-07-12 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20190712_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
