# Generated by Django 2.2.2 on 2019-07-12 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20190713_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
