# Generated by Django 2.2.2 on 2019-07-16 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20190713_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
